services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: encurtai
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
